### PR TITLE
Add SimpleBuildStep support for ApkPublisher

### PR DESCRIPTION
**Pull request by bluesliverx**
Enables workflow/pipeline support

### CODE REVIEW

**Comment by bluesliverx** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-37892

**Comment by orrc** [comment]
Thanks! I've only had a brief look so far, but it seems reasonable — I'll test it out soon and make a new release certainly before [Jenkins World](http://jenkinsworld.com/) :)

**Comment by bluesliverx** [comment]
I've been testing it out too - it's not quite ready yet since it seems to do nothing at the moment.  It may be because the run is not an abstract build.  I'll try to get some more testing in tonight with it.

**Comment by bluesliverx** [comment]
I had to change around most things to use the Run class instead of AbstractBuild, with the major place being in variable expansion.  Pipeline builds don't have the methods necessary to expand variables completely as you have it written currently.  However, after reading up about how this should work for pipeline builds, you can do variable expansion quite easily in the groovy DSL and don't really need env/token macro expansion in pipeline builds, so this shouldn't be an issue. I preserved existing behavior for the plugin and have confirmed it now works for pipeline builds.

Can you please add this documentation to the wiki once you have it released?
To use this plugin in a pipeline script, see the example below. 
```
step([$class: 'ApkPublisher',
	  googleCredentialsId: 'My Credentials Name',
	  apkFilesPattern: 'android.apk',
	  expansionFilesPattern: '',
	  usePreviousExpansionFilesIfMissing: false,
	  trackName: 'production',
	  rolloutPercentage: '100%',
	  recentChangeList: [[language: 'en-US', text:'Here are my release notes']]
])
```

**Comment by orrc** [comment]
I discovered that I had already implemented Pipeline support myself earlier this year, and had the (similar-looking) code on a branch on my laptop…

I've pushed that code, added support for the `ReleaseTrackAssignmentBuilder` as well, integrated the Structs plugin so that the the ugly `step([$class: 'wtf'])` syntax isn't required, tested everything, made a release (version 1.5), and updated the documentation on the wiki.

Let me know if you see any problems :)

**Comment by bluesliverx** [comment]
Looks great, thanks!

**Pull request closed without merging**
