### PR TITLE
Support Android App Bundle Upload Capability

### PR DESCRIPTION
**Pull request by andrewjapar**
- Modify view on config.jelly
- Add timeout when uploading AAB
- Separate Aab and Apk post build action
- Create new publisher for AAB
- Remove expansion file capabilities on AAB

### CODE REVIEW

**Comment by hetang** [comment]
@orrc any update on merging this PR?

**Comment by robotsquidward** [comment]
🔔 @orrc 🔔 just pinging you on this PR.  Thanks so much for your awesome work on this plugin, excited to publish bundles from Jenkins!

**Comment by andrewjapar** [comment]
> 🔔 @orrc 🔔 just pinging you on this PR. Thanks so much for your awesome work on this plugin, excited to publish bundles from Jenkins!

Thanks bro

**Comment by orrc** [comment]
Thanks for the notifications.. I hadn't seen the original ones, sorry.

@jhansche and I had already discussed the design for including AAB support ([JENKINS-53067](https://issues.jenkins-ci.org/browse/JENKINS-53067)) — our idea was to keep the existing "Upload Android APKs" build step, and in there automatically detect whether you're uploading an APK or AAB, and make the appropriate API calls behind the scenes.

Joe started work on it, and made some changes to the plugin already, but I don't know if he got a chance to continue looking into things.

Anyway, this PR is basically a copy-paste of the existing code.  Which isn't ideal, however it could also be seen as a good thing: we could consider merging this and releasing in the near future — then there would be two distinct (if near-identical) upload build steps: one for APKs and one for AABs.

Then in a future release we could implement the automatic detection of AAB files as part of the original upload build step, and ideally remove this code.  Though that's potentially not great for backwards compatibility, and then for maintainability of this plugin… 🤔

**Comment by jhansche** [comment]
Unfortunately I have not had any free time lately to resolve the multi-node test issues from the previous PR, nor get back to refactoring this for supporting AAB.

I intentionally did not go the copy-paste route the first time around, because I wanted to leave the code in a better and more maintainable state, rather than creating 2 classes (and other related components) that are nearly identical. Also, from personal experience, it's better to spend the development effort up front, so that you don't have to worry about cleaning up the technical debt later -- because again from personal experience, that cleanup is much less likely to happen once a working solution has been created.

I do agree with @orrc that this could be a relatively quick stopgap that at least gets AAB support out there, until we can spend more time on refactoring it. That also means that in the future we'll have to spend more time if we refactor it again later, to ensure that the upgrade path from this version to the next version will properly migrate those build steps and configurations.

**Comment by PankajS24** [comment]
Do you guys have any update on this?

**Comment by sambit15k** [comment]
Hi Team,
Please merge the the request .
I am able to push android application bundles via this plugin .
image
Those who are looking for the plugin here is the one which i have builded on my machine - 
https://github.com/sambit15k/Android-App-Bundle-Jenkins-Plugin/raw/master/google-play-android-publisher-2.1-SNAPSHOT.hpi

**Comment by jhansche** [comment]
@orrc has started a branch with support for specifying a file pattern of _either_ `*.aab` or `*.apk`, at https://github.com/jenkinsci/google-play-android-publisher-plugin/tree/feature/add-aab-support
I've installed this version of the plugin but I haven't had a chance to test it yet.

**Comment by Tokenyet** [comment]
Thanks to @sambit15k, that works for me to upload aab!

**Comment by orrc** [comment]
Ask Joe mentioned, we worked on a PR to provide seamless support for uploading AAB files, using the existing build steps.

i.e. You can just change the file pattern from `**/*.apk` to `**/*.aab` in your job configuration (or omit the file pattern parameter altogether, if you're using the Pipeline build step), and things should work as expected.

I've done a bunch of manual (and automated) testing, but if you'd like to try it and give feedback, you can find the link and more information on #19.

**Comment by orrc** [comment]
Thanks for your help, and patience!

Version 3.0 of the plugin has been released, which includes AAB support.

**Pull request closed without merging**
