### PR TITLE
Support for Google Play Console Internal test track.

### PR DESCRIPTION
**Pull request by sergebeauchampGoogle**
The Google Play Console supports a new Internal test track, see:

https://support.google.com/googleplay/android-developer/answer/3131213

This is available through the API by targeting the 'internal' track.

### CODE REVIEW

**Comment by orrc** [comment]
Oh, nice, so it just works — I was going to try out just adding "internal" today to see whether it would work! :)

Thanks for the code, and the insight about the versionCodes being separate.

I will give this some testing, and make a release this week — I have a couple of other fixes I need to release as well.

**Comment by sergebeauchampGoogle** [comment]
Actually, I just checked, and the restriction to have a unique APK per track is not yet lifted for the internal track.

I'll add another pull request to update this accordingly.

**Comment by tbsandee** [comment]
@maxhille that's good to know, if it's true. It didn't at first, failing with a deployment error. Maybe Google started mapping alpha to internal by default.

**Comment by darthg8r** [comment]
I guess I'll clone and build this myself...  It'd be nice to get this released guys.

**Comment by maxhille** [comment]
@tbsandee Unfortunately, 'internal' does **not** seem to also update when uploading to alpha now. I think it 'worked'/happened once but not again. I am confused now.

**Comment by mseroczynski** [comment]
Anything is currently blocking this PR? It's functionality seems really useful.

**Comment by orrc** [comment]
In order to release, it would be good to know whether these changes actually work — you can help by giving feedback on the [plugin build that includes these changes](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fgoogle-play-android-publisher-plugin/detail/PR-8/1/artifacts).

In particular, it would be good to know whether [this logic](https://github.com/jenkinsci/google-play-android-publisher-plugin/pull/8/files#diff-4ab01d22ab81b48b3fde067cba8c9185R95) which is supposedly different to the other tracks (or not, according to [comment #3](https://github.com/jenkinsci/google-play-android-publisher-plugin/pull/8#issuecomment-374593470)‽) works as expected — i.e. can you upload APKs to _internal_ and then successfully upload newer APKs to _alpha_ or _beta_ with this plugin?

**Comment by dmarjanovic** [comment]
I built plugin directly from this PR and all worked as expected with my single APK+deobfuscation file deployments.

> can you upload APKs to internal and then successfully upload newer APKs to alpha or beta with this plugin?

Yes, I used parametrized job so with the same job I was able to publish APK to Internal test track, then with 2nd build to publish APK with incremented versionCode to Alpha track, then with 3rd build to publish newer APK to Beta track, 4rd build again to Internal test and so on. Debfuscation file was always getting uploaded successfully with each APK too so for me it worked perfectly with all tracks.
screen shot 2018-05-07 at 10 15 20 pm

@orrc is any more testing needed or you think there may be progress with this PR? Thank you.

👍

**Comment by mlazowik** [comment]
@orrc pinging in case you missed this :)

**Comment by cwiley982** [comment]
It seems like this PR is really close to getting released since @dmarjanovic tested it and found that it works. Is there anything we can do to help move it along to being merged? We plan on using it as soon as it's released so we'd love to have it soon!

**Comment by darthg8r** [comment]
I gave up on waiting for the PR to be accepted.  I ended up downloading the CI package and installing it and have been using it for a month.

**Comment by orrc** [comment]
Sorry for the delay. Thanks to Serge for the patch, @dmarjanovic for testing (again), and fewer thanks to those who tested but didn't give any feedback… ;)

This has been merged, and version 1.8 of the plugin has been released which includes uploading to the internal track.

**Comment by cmarcelk** [comment]
Thanks for the merge and release. We're using this starting today!

**Pull request closed without merging**
